### ISSUE TITLE
Drive Link to start grid model is broken

### ISSUE THREAD

**Issue by jkb018** [MapStudioProject/TrackStudioDocs#2]
https://github.com/MapStudioProject/TrackStudioDocs/blob/71210d3cce20256d558ed9fadf0c1645ed8e9730/tutorial/Start.html#L1116

When you open the link, you will get an error that the file does not exist.

**Comment by KillzXGaming** [comment]
Should work https://github.com/MapStudioProject/TrackStudioDocs/commit/caa9343eafae8b8ed1f07cb1b513d2a7301f7795
